name: PR
on:
  pull_request:
    paths:
      - "**.go"
      - "**.yml"
      - "**.yaml"
      - "Makefile"
env:
  GOPROXY: https://proxy.golang.org

jobs:
  # Runs before all other jobs
  # builds the minikube binaries
  build_master:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
        stable: true
    - name: checkout master
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Download Dependencies
      run: go mod download
    - name: Build Binaries
      run: |
        git branch --show-current
        make benchmark
    - uses: actions/upload-artifact@v1
      with:
        name: skaffold_master
        path: out/

  build_branch:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
          stable: true
      - name: checkout branch
        uses: actions/checkout@v2
      - name: Download Dependencies
        run: go mod download
      - name: Build Binaries
        run: |
          git branch --show-current
          make benchmark
      - uses: actions/upload-artifact@v1
        with:
          name: skaffold_branch
          path: out/

  benchmark:
    needs: [build_branch, build_master]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
          stable: true

      - uses: actions/download-artifact@v2
        with:
          name: skaffold_branch
          path: bench_master/

      - uses: actions/download-artifact@v2
        with:
          name: skaffold_branch
          path: bench_branch/

      - name: Compare benchmarks
        run: |
          benchstat -delta-test none -html bench_master/benchmark bench_branch/benchmark > benchdelta.html

      - uses: actions/upload-artifact@v1
        with:
          name: benchdelta
          path: benchdelta.html

      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: benchdelta.html
